title = "Py-Tower-Defense-Config"

[general]
    original_frame_rate=60
    max_frame_rate=90
    min_frame_rate=15
    original_zoom=1
    original_time_speed=1

    max_zoom=20
    min_zoom=0.01
    zoom_speed=1.03

    max_x=inf
    max_y=inf



[towers.canon]
    mix_color="LIGHT_GREY"




[attack_towers.home]
    type="Home"
    attack="HomeAttack"
    color="GOLD2"
    size=30
    range=100
    price=+inf
    max_life=500
    num_targets=5
    damage=100
    atk_rate=20


[attack_towers.archery]
    type="Archery"
    attack="ArcherAttack"
    color="VIOLET"
    size=20
    range=600
    price=300
    max_life=200
    num_targets=10
    damage=20
    atk_rate=25

[attack_towers.magic]
    type="Magic"
    attack="MagicAttack"
    color="BLUE"
    size=20
    range=400
    price=500
    max_life=200
    num_targets=3
    damage=50
    atk_rate=60

[attack_towers.bomb]
    type="Bomb"
    attack="BombAttack"
    color="BLACK"
    size=20
    range=700
    price=1000
    max_life=100
    num_targets=1
    damage=350
    atk_rate=150


[effect_towers.damage]
    type="DamageBoost"
    color="CREA2"
    size=15
    range=100
    price=1000
    max_life=200
    power_up_factor=2
    target_type=2

[effect_towers.atkrate]
    type="AtkRateBoost"
    color="CREA1"
    size=15
    range=100
    price=1000
    max_life=200
    power_up_factor=2
    target_type=2

[effect_towers.range]
    type="RangeBoost"
    color="CREA3"
    size=15
    range=100
    price=1000
    max_life=200
    power_up_factor=2
    target_type=2

[effect_towers.canon_speed]
    type="CanonSpeedBoost"
    color="CREA4"
    size=15
    range=100
    price=1500
    max_life=200
    power_up_factor=2
    target_type=2



[zombies.classic]
    type="Classic"
    color="GREEN"
    max_life=200
    speed=0.4
    range=1
    damage=10
    atk_rate=60
    size=10
    value=50

[zombies.tank]
    type="Tank"
    color="DARK_GREEN"
    max_life=1000
    speed=0.2
    range=3
    damage=50
    atk_rate=120
    size=15
    value=200

[zombies.speedy]
    type="Speedy"
    color="YELLOW"
    max_life=200
    speed=1
    range=2
    damage=20
    atk_rate=90
    size=13
    value=100

[zombies.random]
    type="Random"
    color="BROWN"
    mini_max_life=100
    maxi_max_life=3000
    mini_speed=0.2
    maxi_speed=2
    range=4
    mini_damage=5
    maxi_damage=30
    mini_atk_rate=6
    maxi_atk_rate=120
    mini_size=10
    maxi_size=30
    value=500

[zombies.healer]
    type="Healer"
    color="LIGHT_GREEN"
    max_life=400
    speed=0.30
    range=2
    damage=25
    atk_rate=100
    size=18
    value=1000
        special_parameters=["special_atk_rate", "special_range", "special_heal", "special_pause"]
        special_atk_rate=80
        special_range=150
        special_heal=200
        special_pause=40

[attack]


[animation]

[animation.circular_explosion]
    expansion_life_time = 40
    disappear_life_time = 60

[animation.particle_explosion]
    mini_num_particles=10
    maxi_num_particles=80

[animation.particle_explosion.particle]
    mini_life_time=20
    maxi_life_time=50
    mini_size_factor=0.2
    maxi_size_factor=0.8
    mini_color_variation=-20
    maxi_color_variation=20
    mini_speed=0.3
    maxi_speed=4
    mini_alpha=100
    maxi_alpha=255
    mini_speed_decrease=0.7
    maxi_speed_decrease=1
    mini_alpha_decrease=0.4
    maxi_alpha_decrease=1

[animation.particle_explosion_zombie]
    mini_num_particles=8
    maxi_num_particles=30

[animation.particle_explosion_zombie.particle]
    mini_life_time=20
    maxi_life_time=40
    mini_size_factor=0.2
    maxi_size_factor=0.5
    mini_color_variation=-20
    maxi_color_variation=20
    mini_speed=0.3
    maxi_speed=2
    mini_alpha=100
    maxi_alpha=255
    mini_speed_decrease=0.7
    maxi_speed_decrease=1
    mini_alpha_decrease=0.6
    maxi_alpha_decrease=1


[animation.tower_bop]
    life_time = 20
    size_increase=0.3

[animation.circular_effect]
    alpha=40
    life_time=35







[wave]



[wave.1]
max_x=1000
max_y=1000
min_zoom=0.5
max_zoom=5

[wave.2-10]
max_x=1500
max_y=1500
min_zoom=0.4

[wave.5]
max_x=2000

[wave.2]
